"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const providers=[{id:"google",label:"Google",icon:"G"},{id:"discord",label:"Discord",icon:"◌"},{id:"twitch",label:"Twitch",icon:"◈"}];
export function LoginForm(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false),[frozen,setFrozen]=useState(false);const router=useRouter();
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const e=p.get("error");if(e)setError(e==="provider"?"Não foi possível concluir o login social.":decodeURIComponent(e))},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok){setError(j.error||"Não foi possível entrar.");setFrozen(Boolean(j.frozen));}else router.push("/");setLoading(false)}
 return <div className="authForm"><div className="socialAuthGroup"><div className="authSectionLabel">Entrar com</div><div className="socialAuth">{providers.map(p=><a className="oauthButton" aria-label={`Continuar com ${p.label}`} href={`/api/auth/oauth/${p.id}`} key={p.id}><span>{p.icon}</span>{p.label}</a>)}</div></div><div className="authDivider"><span>ou com e-mail</span></div><form className="stack" onSubmit={submit}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="voce@email.com" required/></label><label>Senha<div className="passwordField"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?"text":"password"} autoComplete="current-password" placeholder="Sua senha" required/><button type="button" className="passwordToggle" onClick={()=>setShow(!show)}>{show?"Ocultar":"Mostrar"}</button></div></label><div className="formMeta"><label className="check"><input type="checkbox"/> Lembrar neste dispositivo</label><span className="muted">Recuperação em breve</span></div>{error&&<div className="formError">{error}</div>}<button className="btn authSubmit" disabled={loading}>{loading?"Entrando…":"Entrar no Groov"}</button>{frozen&&<button type="button" className="btn secondary authSubmit" disabled={loading} onClick={async()=>{setLoading(true);const rr=await fetch("/api/account/unfreeze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const jj=await rr.json();if(rr.ok)router.push("/");else setError(jj.error||"Não foi possível reativar a conta.");setLoading(false)}}>Reativar minha conta</button>}</form><div className="authFooter">Ainda não tem conta? <a href="/register">Criar conta</a></div></div>
}
