"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
const providers=[{id:"google",label:"Google",icon:"G"},{id:"discord",label:"Discord",icon:"◌"},{id:"twitch",label:"Twitch",icon:"◈"}];
export function RegisterForm(){
 const [form,setForm]=useState({email:"",username:"",displayName:"",password:"",confirmPassword:"",acceptTerms:false}),[error,setError]=useState(""),[loading,setLoading]=useState(false);const router=useRouter();
 const set=(k:string,v:string|boolean)=>setForm({...form,[k]:v});
 const strength=useMemo(()=>{let n=0;if(form.password.length>=8)n++;if(/[A-Za-z]/.test(form.password))n++;if(/\d/.test(form.password))n++;if(/[^A-Za-z0-9]/.test(form.password))n++;return n},[form.password]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(form.password!==form.confirmPassword)return setError("As senhas não coincidem.");if(!form.acceptTerms)return setError("Você precisa aceitar os termos para continuar.");setLoading(true);const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)setError(j.error||"Não foi possível criar sua conta.");else router.push("/");setLoading(false)}
 return <div className="authForm"><div className="socialAuthGroup"><div className="authSectionLabel">Começar com</div><div className="socialAuth">{providers.map(p=><a className="oauthButton" aria-label={`Continuar com ${p.label}`} href={`/api/auth/oauth/${p.id}`} key={p.id}><span>{p.icon}</span>{p.label}</a>)}</div></div><div className="authDivider"><span>ou crie com e-mail</span></div><form className="stack" onSubmit={submit}><div className="grid two"><label>Nome de exibição<input value={form.displayName} onChange={e=>set("displayName",e.target.value)} placeholder="Como você quer ser chamado?" required/></label><label>Username<input value={form.username} onChange={e=>set("username",e.target.value.replace(/\s/g,""))} placeholder="seuusername" minLength={3} maxLength={24} required/><small className="helper">3–24 caracteres · letras, números e _</small></label></div><label>E-mail<input value={form.email} onChange={e=>set("email",e.target.value)} type="email" autoComplete="email" placeholder="voce@email.com" required/></label><label>Senha<div className="passwordField"><input value={form.password} onChange={e=>set("password",e.target.value)} type="password" autoComplete="new-password" placeholder="Crie uma senha forte" minLength={8} required/></div></label>{form.password&&<div className="strength"><div className="strengthBars">{[1,2,3,4].map(i=><i key={i} className={strength>=i?"filled":""}/>)}</div><span>{strength<2?"Fraca":strength<4?"Boa":"Forte"}</span></div>}<label>Confirmar senha<input value={form.confirmPassword} onChange={e=>set("confirmPassword",e.target.value)} type="password" autoComplete="new-password" placeholder="Repita sua senha" required/></label><label className="terms check"><input type="checkbox" checked={form.acceptTerms} onChange={e=>set("acceptTerms",e.target.checked)}/> Eu aceito os termos de uso e a política de privacidade.</label>{error&&<div className="formError">{error}</div>}<button className="btn authSubmit" disabled={loading}>{loading?"Criando conta…":"Criar minha conta"}</button></form><div className="authFooter">Já tem uma conta? <a href="/login">Entrar</a></div></div>
}
